<template>
  <div v-if="loading" :style="mai" class="loadingio-spinner-rolling-wvoglj404">
    <div class="ldio-xz9pwqt2g">
      <div :style="style"></div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Spinner',
  props: {
    loading: {
      type: Boolean,
      required: true,
      default: false,
    },
    color: {
      type: String,
      default: '#333333',
    },
    radius: {
      type: String,
      default: '20',
    },
  },
  computed: {
    style() {
      return `border: 2px solid ${this.color ? this.color : '#FFFFFF'};
      border-top-color: transparent;
      width: ${this.radius / 2}px;
      height: ${this.radius / 2}px;
      top: ${this.radius / 2}px;
      left: ${this.radius / 2}px;
      `;
    },
    mai() {
      return `width: ${this.radius}px;
      height: ${this.radius}px;`;
    },
  },
};
</script>

<style lang="scss" scoped>
@keyframes ldio-xz9pwqt2g {
  0% {
    transform: translate(-50%, -50%) rotate(0deg);
  }
  100% {
    transform: translate(-50%, -50%) rotate(360deg);
  }
}
.ldio-xz9pwqt2g div {
  position: absolute;
  border: 2px solid #274690;
  border-top-color: transparent;
  border-radius: 50%;
  display: flex;
}
.ldio-xz9pwqt2g div {
  animation: ldio-xz9pwqt2g 0.6711409395973155s linear infinite;
}
.loadingio-spinner-rolling-wvoglj404 {
  position: relative;
  display: flex;
  justify-items: center;
  align-items: center;
  background: transparent;
}
.ldio-xz9pwqt2g {
  display: flex;
  justify-content: center;
  align-items: center;
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0;
}
.ldio-xz9pwqt2g div {
  box-sizing: content-box;
}

/* generated by https://loading.io/ */
</style>
